# Do NOT edit this file!
# It was generated by IdlC class idl.json.python.ProxyAsnVisitor.

#
# Section generated from "/home/nb/builds/MEGA/px2-3.0.0-3.0.9-branch-20140613-none-release-none-pdu-raritan/fwcomponents/mkdist/tmp/px2_final/jsonrpcd/src/idl/NameService.idl"
#

import raritan.rpc
from raritan.rpc import Interface, Structure, ValueObject, Enumeration, typecheck, DecodeException

# interface
class NameService(Interface):
    idlType = "jsonrpc.NameService:1.0.0"

    def lookup(self, name):
        agent = self.agent
        typecheck.is_string(name, AssertionError)
        args = {}
        args['name'] = name
        rsp = agent.json_rpc(self.target, 'lookup', args)
        _ret_ = Interface.decode(rsp['_ret_'], agent)
        typecheck.is_remote_obj(_ret_, DecodeException)
        return _ret_
