# Do NOT edit this file!
# It was generated by IdlC class idl.json.python.ProxyAsnVisitor.

#
# Section generated from "/home/nb/builds/MEGA/px2-3.0.0-3.0.9-branch-20140613-none-release-none-pdu-raritan/fwcomponents/mkdist/tmp/px2_final/libisys/src/idl/Production.idl"
#

import raritan.rpc
from raritan.rpc import Interface, Structure, ValueObject, Enumeration, typecheck, DecodeException

# interface
class Production(Interface):
    idlType = "production.Production:1.0.0"

    def enterFactoryConfigMode(self, password):
        agent = self.agent
        typecheck.is_string(password, AssertionError)
        args = {}
        args['password'] = password
        rsp = agent.json_rpc(self.target, 'enterFactoryConfigMode', args)
        _ret_ = rsp['_ret_']
        typecheck.is_int(_ret_, DecodeException)
        return _ret_

    def leaveFactoryConfigMode(self):
        agent = self.agent
        args = {}
        rsp = agent.json_rpc(self.target, 'leaveFactoryConfigMode', args)

    def isFactoryConfigModeEnabled(self):
        agent = self.agent
        args = {}
        rsp = agent.json_rpc(self.target, 'isFactoryConfigModeEnabled', args)
        _ret_ = rsp['_ret_']
        typecheck.is_bool(_ret_, DecodeException)
        return _ret_
